[package]
edition.workspace      = true
license.workspace      = true
name                   = "prose_corpus"
publish                = false
repository.workspace   = true
rust-version.workspace = true

[package.metadata.cargo-machete]
ignored = ["libcst"]

[dependencies]
clap               = { version = "4.5", features = ["derive"] }
fs-err             = "3"
ignore             = "0.4"
itertools          = "0.15"
libcst             = { version = "1.8", default-features = false }
rand               = "0.10"
rayon              = "1.10"
ruff_python_ast    = "=0.0.5"
ruff_python_parser = "=0.0.5"
ruff_python_stdlib = "=0.0.5"
ruff_text_size     = "=0.0.5"
rustc-hash         = "2"
serde              = { version = "1.0", features = ["derive"] }
serde_json         = "1.0"
tabled             = { version = "0.21", default-features = false, features = ["std"] }

[lints]
workspace = true
