import { defineRouteMiddleware, type StarlightRouteData } from '@astrojs/starlight/route-data'
import { getCollection }                                  from 'astro:content'

import type { PrimitiveStability } from '../shared/registries'
import { PRIMITIVES_LABEL }        from './sidebar'

type SidebarEntry = StarlightRouteData['sidebar'][number]

const stabilityOf = new Map(
  (await getCollection('docs', entry => entry.data.stability !== undefined))
    .map(entry => [entry.id, entry.data.stability])
)

const idOf = (href: string): string => href.replace(/^\/|\/$/g, '')

const subgroup = (label: string, entries: SidebarEntry[]): SidebarEntry => ({
  badge     : undefined,
  collapsed : false,
  entries   : entries,
  label     : label,
  type      : 'group'
})

// Splits the autogenerated primitives group into its public-surface and
// crate-internal halves, read from each page's `stability` frontmatter,
// leaving the unclassified overview link ahead of the two subgroups.
export const onRequest = defineRouteMiddleware(context => {
  const group = context.locals.starlightRoute.sidebar.find(
    (entry): entry is Extract<SidebarEntry, { type: 'group' }> =>
      entry.type === 'group' && entry.label === PRIMITIVES_LABEL
  )
  if (group === undefined) return
  const links = (stability: PrimitiveStability): SidebarEntry[] =>
    group.entries.filter(
      entry => entry.type === 'link' && stabilityOf.get(idOf(entry.href)) === stability
    )
  group.entries = [
    ...group.entries.filter(entry => entry.type !== 'link' || !stabilityOf.has(idOf(entry.href))),
    subgroup('Public Surface', links('public')),
    subgroup('Crate Internal', links('internal'))
  ]
})
