import type { StarlightUserConfig } from '@astrojs/starlight/types'

import { FAMILY_ORDER } from '../shared/registries'

export const PRIMITIVES_LABEL = 'Primitives'

const capitalize = (slug: string): string => slug[0].toUpperCase() + slug.slice(1)

const autogenerated = (label: string, directory: string) => ({
  items : [{ autogenerate: { directory } }],
  label : label
})

// Sections stay in reading order rather than alphabetized, and the primitives
// group is left whole for the route middleware's stability split.
export const sidebar: StarlightUserConfig['sidebar'] = [
  autogenerated('Usage',        'usage'),
  autogenerated('Reference',    'reference'),
  autogenerated('Integrations', 'integrations'),
  {
    items : [
      { label: 'Overview',    slug: 'rules'             },
      { label: 'Composition', slug: 'rules/composition' },
      ...FAMILY_ORDER.map(family => autogenerated(capitalize(family), `rules/${family}`))
    ],
    label : 'Rules'
  },
  autogenerated(PRIMITIVES_LABEL, 'primitives')
]
