import type { StarlightUserConfig } from '@astrojs/starlight/types'

import { FAMILY_ORDER } from '../shared/registries'
import { titleCase }    from '../shared/title-case'

export const PRIMITIVES_LABEL = 'Primitives'

const autogenerated = (label: string, directory: string) => ({
  items: [{ autogenerate: { directory } }],
  label
})

// Sections stay in reading order rather than alphabetized, and the primitives
// group is left whole for the route middleware's stability split.
export const sidebar: StarlightUserConfig['sidebar'] = [
  autogenerated('Usage',        'usage'),
  autogenerated('Reference',    'reference'),
  autogenerated('Integrations', 'integrations'),
  {
    items : [
      { label: 'Overview',    slug: 'rules'             },
      { label: 'Composition', slug: 'rules/composition' },
      ...FAMILY_ORDER.map(family => autogenerated(titleCase(family), `rules/${family}`))
    ],
    label : 'Rules'
  },
  autogenerated(PRIMITIVES_LABEL, 'primitives')
]

if (import.meta.vitest) {
  const { describe, expect, test } = import.meta.vitest

  const groups = sidebar as { items: unknown[]; label: string }[]
  const byLabel = (label: string) => groups.find(group => group.label === label)

  describe('sidebar', () => {
    test.each([
      { name: 'opens with the usage autogeneration',        label: 'Usage',        directory: 'usage'        },
      { name: 'follows with reference autogeneration',      label: 'Reference',    directory: 'reference'    },
      { name: 'follows with integrations autogeneration',   label: 'Integrations', directory: 'integrations' },
      { name: 'closes with the whole primitives group',     label: PRIMITIVES_LABEL, directory: 'primitives' }
    ])('$name', ({ label, directory }) => {
      expect(byLabel(label)?.items).toEqual([{ autogenerate: { directory } }])
    })

    test('leads the rules group with the overview and composition links', () => {
      const items = byLabel('Rules')?.items as { label: string; slug: string }[]
      expect(items.slice(0, 2)).toEqual([
        { label: 'Overview',    slug: 'rules'             },
        { label: 'Composition', slug: 'rules/composition' }
      ])
    })

    test.each(FAMILY_ORDER.map(family => ({ family })))('carries a $family autogeneration under rules', ({ family }) => {
      const items = byLabel('Rules')?.items as { items: unknown[]; label: string }[]
      expect(items).toContainEqual({ items: [{ autogenerate: { directory: `rules/${family}` } }], label: titleCase(family) })
    })
  })
}
