comment: false

coverage:
  precision : 2
  round     : down

  status:
    patch: &targets
      default:
        target: 95%
      rust:
        target : 95%
        flags  : [rust]

    project: *targets

flags:
  rust:
    paths        : [crate/src]
    carryforward : true
