comment: false

coverage:
  precision : 2
  round     : down

  status:
    patch:
      default:
        target: 95%
      rust:
        target : 95%
        flags  : [rust]
      site:
        target : 95%
        flags  : [site]

    project:
      default:
        target: 95%
      rust:
        target : 95%
        flags  : [rust]
      site:
        target : 95%
        flags  : [site]

flags:
  rust:
    paths        : [crate/src]
    carryforward : true
  site:
    paths        : [site/.vitepress]
    carryforward : true
