comment: false

coverage:
  precision : 2
  round     : down

  status:
    patch: &targets
      default:
        target: &target 95%
      rust: &status
        flags  : [rust]
        target : *target
      site:
        <<     : *status
        flags  : [site]

    project: *targets

flags:
  rust: &flag
    carryforward : true
    paths        : [crate/src, wasm/src]
  site:
    <<    : *flag
    paths : [site/.vitepress]
