changelog:
  categories:
    - title: ✨ Features
      labels:
        - 🦉 engine
        - 🪜 alignment
        - 🪉 ordering
        - 🪶 formatting
        - 🧶 lint
    - title: 🐞 Bugs
      labels:
        - 🐞 bug
    - title: 🪄 CLI
      labels:
        - 🪄 cli
    - title: 📰 Docs
      labels:
        - 📰 docs
    - title: 🗜️ Build
      labels:
        - 🗜️ build
    - title: 🧱 Internals
      labels:
        - ⚖️ tests
        - 🗺️ architecture
    - title: Other
      labels:
        - "*"
