#!/usr/bin/env -S bash -euo pipefail
#MISE alias="links"
#MISE description="Check the built site for broken internal links with `lychee`"
#MISE depends=["site:press"]
#MISE dir="site"

lychee --offline \
  --root-dir "$PWD/.vitepress/dist" \
  --fallback-extensions html \
  .vitepress/dist
