#!/usr/bin/env -S bash -euo pipefail
#MISE alias       = "links"
#MISE depends     = ["site:press"]
#MISE description = "Check the built site for broken internal links with `lychee`"
#MISE dir         = "site"

lychee \
  --fallback-extensions html \
  --offline \
  --root-dir "$PWD/.vitepress/dist" \
  .vitepress/dist
