#!/usr/bin/env -S bash -euo pipefail
#MISE alias="press"
#MISE description="Produce the static docs bundle at `site/.vitepress/dist`"
#MISE depends=["rust:bin", "site:bake", "wasm:pack"]
#MISE dir="site"

bunx vitepress build
