#!/usr/bin/env -S bash -euo pipefail
#MISE alias       = "press"
#MISE depends     = ["rust:build", "site:bake", "wasm:pack"]
#MISE description = "Produce the static docs bundle at `site/.vitepress/dist`"
#MISE dir         = "site"
#MISE sources     = [
#MISE   "../.mise/config.toml",
#MISE   "../Cargo.lock",
#MISE   "../Cargo.toml",
#MISE   "../crate/Cargo.toml",
#MISE   "../crate/pyproject.toml",
#MISE   "../crate/src/**/*.rs",
#MISE   "../crate/tests/fixtures/**/*",
#MISE   "**/*",
#MISE   "!.vitepress/.temp/**/*",
#MISE   "!.vitepress/dist/**/*",
#MISE   "!.vitepress/tests/wasm/pkg/**/*",
#MISE   "!coverage/**/*",
#MISE   "!node_modules/**/*"
#MISE ]

bunx vitepress build
