[[platforms]]
label     = "🐧 Linux x86_64"
manylinux = "auto"
name      = "linux-x86_64"
pattern   = "*manylinux*x86_64.whl"
runner    = "ubuntu-latest"
target    = "x86_64-unknown-linux-gnu"

[[platforms]]
label     = "🐧 Linux aarch64"
manylinux = "auto"
name      = "linux-aarch64"
pattern   = "*manylinux*aarch64.whl"
runner    = "ubuntu-24.04-arm"
target    = "aarch64-unknown-linux-gnu"

[[platforms]]
label   = "🍎 macOS x86_64"
name    = "macos-x86_64"
pattern = "*macosx*x86_64.whl"
runner  = "macos-15-intel"
target  = "x86_64-apple-darwin"

[[platforms]]
label   = "🍎 macOS aarch64"
name    = "macos-aarch64"
pattern = "*macosx*arm64.whl"
runner  = "macos-latest"
target  = "aarch64-apple-darwin"

[[platforms]]
label   = "🪟 Windows x86_64"
name    = "windows-x86_64"
pattern = "*win_amd64.whl"
runner  = "windows-latest"
target  = "x86_64-pc-windows-msvc"

[[platforms]]
label   = "🚢 sdist"
name    = "sdist"
pattern = "*.tar.gz"
