[workspace]
members  = ["crate", "wasm"]
resolver = "3"

[workspace.lints.clippy]
nonminimal_bool          = "warn"
overly_complex_bool_expr = "warn"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage)"] }

[workspace.package]
edition      = "2024"
license      = "MIT"
repository   = "https://github.com/Jybbs/prose"
rust-version = "1.97.1"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package]
insta              = { opt-level = 2 }
prose              = { codegen-units = 16 }
ruff_python_ast    = { opt-level = 2 }
ruff_python_parser = { opt-level = 2 }
ruff_python_trivia = { opt-level = 2 }
ruff_source_file   = { opt-level = 2 }
similar            = { opt-level = 2 }

[profile.probe]
debug-assertions = true
inherits         = "release"
lto              = "off"
overflow-checks  = true
panic            = "unwind"
strip            = "none"

[profile.profiling]
debug    = "full"
inherits = "release"
lto      = false
strip    = "none"

[profile.release]
codegen-units = 16
lto           = "fat"
panic         = "abort"
strip         = "symbols"

[profile.release.package]
ruff_python_ast    = { codegen-units = 1 }
ruff_python_parser = { codegen-units = 1 }

[profile.wasm-release]
inherits = "release"
lto      = false
strip    = "debuginfo"
