[settings]
idiomatic_version_file_enable_tools = ["node"]
python.uv_venv_auto                 = "create|source"
task.source_freshness_hash_contents = true

[tools]
bun     = "latest"
maturin = "latest"
python  = "3.14"
rust    = { version = "1.95", components = "llvm-tools-preview" }
uv      = "latest"
