#!/usr/bin/env -S bash -euo pipefail
#MISE description = "Run `clippy` over `prose_wasm` for the `wasm32-unknown-unknown` target"

source "$MISE_PROJECT_ROOT/.mise/lib/wasm.bash"

wasm_cargo clippy -- -D warnings
