#!/usr/bin/env -S bash -euo pipefail
#MISE alias       = "pack"
#MISE depends     = ["wasm:build"]
#MISE description = "Emit the `prose_wasm` web module into `site/public/wasm` and optimize it"
#MISE outputs     = ["site/public/wasm/*"]
#MISE sources     = ["@group:wasm"]

out=site/public/wasm
trap 'rm -rf "$out"' ERR

wasm-bindgen \
  --experimental-reset-state-function \
  --out-dir "$out" \
  --target web \
  "$WASM_ARTIFACT"
wasm-opt -O --output "$out/prose_wasm_bg.wasm.opt" "$out/prose_wasm_bg.wasm"
mv "$out/prose_wasm_bg.wasm.opt" "$out/prose_wasm_bg.wasm"
