#!/usr/bin/env -S bash -euo pipefail
#MISE alias       = "pack"
#MISE depends     = ["wasm:build"]
#MISE description = "Emit the `prose_wasm` web module into `site/public/wasm`"
#MISE outputs     = ["site/public/wasm/*"]
#MISE sources     = [
#MISE   ".mise/config.toml",
#MISE   ".mise/tasks/wasm/build",
#MISE   ".mise/tasks/wasm/pack",
#MISE   "Cargo.lock",
#MISE   "Cargo.toml",
#MISE   "crate/Cargo.toml",
#MISE   "crate/src/**",
#MISE   "wasm/**"
#MISE ]

out=site/public/wasm

wasm-bindgen \
  --experimental-reset-state-function \
  --out-dir "$out" \
  --target web \
  "$WASM_ARTIFACT"
