#!/usr/bin/env bash
#MISE description="Check the built site for broken internal links with `lychee`"
#MISE dir="site"
#MISE tools={"aqua:lycheeverse/lychee" = "latest"}

lychee --root-dir "$PWD/.vitepress/dist" .vitepress/dist
