#!/usr/bin/env bash
#MISE description="Check the built site for broken internal links with `lychee`"
#MISE dir="site"
#MISE wait_for=["press"]
#MISE tools={"aqua:lycheeverse/lychee" = "latest"}

lychee --offline --fallback-extensions html --root-dir "$PWD/dist" dist
