#!/usr/bin/env bash
#MISE description="Generate coverage and upload it to Codecov for the Rust crate"
#MISE tools={"pipx:codecov-cli" = "latest"}

set -euo pipefail

mise run coverage && codecovcli upload-process --flag rust --file target/lcov.info --sha "$SHA"
