# Internal-link deploy gate over the built site. External URLs are excluded so
# network flakiness cannot fail a deploy; they warrant a separate scheduled
# sweep rather than a release-blocking check.
fallback_extensions = ["html"]
exclude             = ['^https?://', '^mailto:']
