<template>
  <table>
    <thead>
      <tr>
        <th>Key</th>
        <th>Type</th>
        <th>Default</th>
        <th>Meaning</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><code>enabled</code></td>
        <td>bool</td>
        <td><code>true</code></td>
        <td>Toggle the rule on or off</td>
      </tr>
    </tbody>
  </table>
</template>
