#!/usr/bin/env -S bash -euo pipefail
#MISE depends     = ["rust:coverage"]
#MISE description = "Upload the Rust coverage report to Codecov"

source "$MISE_PROJECT_ROOT/.mise/lib/codecov.bash"

upload_report rust target/lcov.info
