#!/usr/bin/env -S bash -euo pipefail
#MISE depends     = ["rust:coverage"]
#MISE description = "Upload the Rust coverage report to Codecov"

codecovcli upload-process --file target/lcov.info --flag rust --sha "$SHA"
