#!/usr/bin/env -S bash -euo pipefail
#MISE alias        = "ci"
#MISE depends      = [
#MISE   "lock:check",
#MISE   "repo:audit",
#MISE   "rust:check",
#MISE   "rust:cruft",
#MISE   "rust:lint",
#MISE   "rust:unused",
#MISE   "site:cruft",
#MISE   "site:links",
#MISE   "site:lint",
#MISE   "site:press",
#MISE   "site:test",
#MISE   "site:typecheck",
#MISE   "wasm:smoke"
#MISE ]
#MISE depends_post = ["rust:wheel"]
#MISE description  = "Full local CI sweep"
